### ISSUE TITLE
Create `messaging` extension for the rich manipulation of messages, embeds and attachments

### ISSUE THREAD

**Issue by Mega-JC** [pygame-community/PygameCommunityBot#10]
## Overview

The `messaging` extension should allow for the easy but versatile manipulation of bot messages and their parts, ranging from things like message/ embed creation, editing & cloning to target locations, as well as mass message link/ID fetching and deletion (which can also include non-bot messages).

## Synopsis
TBA

## Technical Details
TBA

## New Bot Commands
All commands can be contained in a cog called `Messaging`.

The `message` root command can also have a `msg` alias for convenience.

**EDIT:**
Due to the large amount of commands and their complexity, this feature implementation will be split into 2 parts.

 1. [x] **Part 1**: #14

    - [x]  **`message`**/**`message send`**: Creates a message with text content and/or embeds (as code blocks) and/or attachments and sends them to the specified destinations.
    - [x] **`message edit`**: Edits a message with new message content and/or embeds and/or attachments.

    - [x] **`message sendtext`**: Creates a message with text content and sends them to the specified destinations.
    - [x] **`message edittext`**: Edits a message with new message text content.

    - [x] **`message clone`**: Clones one or more messages with(out) embeds and/or attachments to the specified destinations.
    - [x] **`message archive`** : Clones a (un)specific amount of messages in the specified date/message range in a channel/thread to the specified destination.

    - [x] **`message extract`**: Fetches the IDs/URLs of a (un)specific amount of messages in the specified date/message range in a channel/thread.

    - [x] **`message pin`**: Pins the specified message(s) in the current channel.
    - [x] **`message pin at`**: Pins the specified message(s) in the specified channel.
    - [x] **`message unpin`**: Unpins the specified message(s) in the current channel.
    - [x] **`message unpin at`**: Unpins the specified message(s) in the specified channel.

2. [ ] **Part 2**

    - [ ] **`message fetch`**: Fetches the IDs/URLs of a (un)specific amount of messages in the specified date/message range in a channel/thread.
    - [ ] **`message fetch pins`**: Fetches the pinned messages in the specified position range in a channel/thread.

    - [ ] **`message delete`**: Deletes the specified messages.
    - [ ] **`message purge`**: Purges a (un)specific amount of messages ((not) by the specified member(s)) in the specified date/message range in a channel/thread.

    - [ ] **`embed`**/**`embed create`**: Creates a message containing 1-10 embeds specified as either JSON/Python code blocks or a message with 1-10 JSON/Python file attachments.
    - [ ] **`embed edit`**: Edits the embed(s) of one or more messages specified as either JSON/Python code blocks or a message with 1-10 JSON/Python file attachments at the specified embed position(s).
    - [ ] **`embed add`**: Adds the embeds specified as either JSON/Python code blocks or a message with 1-10 JSON/Python file attachments to one or more messages.
    - [ ] **`embed get`**: Gets and/or removes all or only the specified attributes of the embeds at the specified position(s) in the specified message(s) as embed data files (JSON/Python), embeds, or both and sends them to the specified location(s).
    - [ ] **`embed cut`**/**`embed move`**: Removes 1-10 embeds at the specified embed position(s) and adds them to the specified message(s).
    - [ ] **`embed copy`**: Copies 1-10 embeds at the specified embed position(s) and adds them to the specified message(s), which may be the same as the initial target message.
    - [ ] **`embed remove`**: Removes 1-10 embeds at the specified embed position(s) from the specified message(s).
    - [ ] **`embed clear`**: Removes all embeds from the specified message(s).

**Comment by Mega-JC** [comment]
# Part 1

## Commands

All commands can be contained in a cog called `Messaging`.

The `message` root command can also have a `msg` alias for convenience.

- [x] **`message`**/**`message send`**: Creates a message with text content and/or embeds (as code blocks) and/orattachments and sends them to the specified destinations.
- [x] **`message edit`**: Edits a message with new message content and/or embeds and/or attachments.

- [x] **`message sendtext`**: Creates a message with text content and sends them to the specified destinations.
- [x] **`message edittext`**: Edits a message with new message text content.

- [x] **`message clone`**: Clones one or more messages with(out) embeds and/or attachments to the specified destinations.
- [x] **`message archive`** : Clones a (un)specific amount of messages in the specified date/message range in a channel/thread to the specified destination.

- [ ] **`message fetch`**: Fetches the IDs/URLs of a (un)specific amount of messages in the specified date/message range in a channel/thread.
- [ ] **`message fetch pins`**: Fetches the pinned messages in the specified position range in a channel/thread.

- [x] **`message extract`**: Fetches the IDs/URLs of a (un)specific amount of messages in the specified date/message range in a channel/thread.
- [ ] **`message delete`**: Deletes the specified messages.
- [ ] **`message purge`**: Purges a (un)specific amount of messages ((not) by the specified member(s)) in the specified date/message range in a channel/thread.

- [x] **`message pin`**: Pins the specified message(s).
- [x] **`message pin at`**: Pins the specified message(s) in the specified channel.
- [x] **`message unpin`**: Pins the specified message(s).
- [x] **`message unpin at`**: Pins the specified message(s) in the specified channel.

- [ ] **`embed`**/**`embed create`**: Creates a message containing 1-10 embeds specified as either JSON/Python code blocks or a message with 1-10 JSON/Python file attachments.
- [ ] **`embed edit`**: Edits the embed(s) of one or more messages specified as either JSON/Python code blocks or a message with 1-10 JSON/Python file attachments at the specified embed position(s).
- [ ] **`embed add`**: Adds the embeds specified as either JSON/Python code blocks or a message with 1-10 JSON/Python file attachments to one or more messages.
- [ ] **`embed get`**: Gets and/or removes all or only the specified attributes of the embeds at the specified position(s) in the specified message(s) as embed data files (JSON/Python), embeds, or both and sends them to the specified location(s).
- [ ] **`embed cut`**/**`embed move`**: Removes 1-10 embeds at the specified embed position(s) and adds them to the specified message(s).
- [ ] **`embed copy`**: Copies 1-10 embeds at the specified embed position(s) and adds them to the specified message(s), which may be the same as the initial target message.
- [ ] **`embed remove`**: Removes 1-10 embeds at the specified embed position(s) from the specified message(s).
- [ ] **`embed clear`**: Removes all embeds from the specified message(s).

**Comment by Mega-JC** [comment]
# Part 2

## Commands

All commands can be contained in a cog called `Messaging`.

The `message` root command can also have a `msg` alias for convenience.

- [ ] **`message fetch`**: Fetches the IDs/URLs of a (un)specific amount of messages in the specified date/message range in a channel/thread.
- [ ] **`message fetch pins`**: Fetches the pinned messages in the specified position range in a channel/thread.

- [ ] **`message delete`**: Deletes the specified messages.
- [ ] **`message purge`**: Purges a (un)specific amount of messages ((not) by the specified member(s)) in the specified date/message range in a channel/thread.

- [ ] **`embed`**/**`embed create`**: Creates a message containing 1-10 embeds specified as either JSON/Python code blocks or a message with 1-10 JSON/Python file attachments.
- [ ] **`embed edit`**: Edits the embed(s) of one or more messages specified as either JSON/Python code blocks or a message with 1-10 JSON/Python file attachments at the specified embed position(s).
- [ ] **`embed add`**: Adds the embeds specified as either JSON/Python code blocks or a message with 1-10 JSON/Python file attachments to one or more messages.
- [ ] **`embed get`**: Gets and/or removes all or only the specified attributes of the embeds at the specified position(s) in the specified message(s) as embed data files (JSON/Python), embeds, or both and sends them to the specified location(s).
- [ ] **`embed cut`**/**`embed move`**: Removes 1-10 embeds at the specified embed position(s) and adds them to the specified message(s).
- [ ] **`embed copy`**: Copies 1-10 embeds at the specified embed position(s) and adds them to the specified message(s), which may be the same as the initial target message.
- [ ] **`embed remove`**: Removes 1-10 embeds at the specified embed position(s) from the specified message(s).
- [ ] **`embed clear`**: Removes all embeds from the specified message(s).

**Comment by Mega-JC** [comment]
Closing this as Part 2 is largely redundant for most use cases.
